apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-jtbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-jtbe
    app.kubernetes.io/part-of: test-app-xuux
  name: test-component-jtbe
  namespace: build-e2e-zhtx-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-jtbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-jtbe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:628bee46cd7978961aaa1f79a3373b3d7a32a8879aea816532150ea3b9d2585e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
